import { ErrorData, FormData } from '@/types/signup';

export const steps = [
  'Email',
  'PersonalInfo',
  'Section B',
  'Section C',
  'Section D',
  'Section E',
];
const contact = { address: '', tel: '' };
export const initialFormData: FormData = {
  step: 1,
  email: '',
  surname: '',
  firstName: '',
  dob: '',
  nationality: '',
  home: contact,
  permanent: contact,
  occupation: contact,
  occupationTel: 0,
  employer: '',
  business: contact,
  nameOfBankers: '',
  employed: '',
  married: '',
  isNigeria: '',
  clubMemberRelative: '',
  dependentRelativeBenin: '',
  residePermanentlyBenin: '',
  otherClubMember: '',
  playSport: '',
  knownAilment: '',
  transferOutOfBenin: '',
  chargedWithCriminalOffense: '',
  marriageDuration: 0,
  numberOfChildren: 0,
  children: [],
  addressYears: '',
  emergencyContact: '',
  disability: '',
  sportSection: '',
  reasonToJoin: '',
  tribe: '',
  numberOfWives: '',
  educations: [],
  workExperiences: [],
  proposerPersonality: '',
  proposerKnown: '',
  // add more fields as needed
};

export const initialErrorData: ErrorData = {
  general: '',
  email: '',
  surname: '',
  firstName: '',
  dob: '',
  nationality: '',
  homeAddress: '',
  homeAddressTel: '',
  permanentAddress: '',
  permanentAddressTel: '',
  occupation: '',
  occupationTel: '',
  employer: '',
  businessAddress: '',
  businessAddressTel: '',
  nameOfBankers: '',
  employed: '',
  married: '',
  isNigeria: '',
  clubMemberRelative: '',
  dependentRelativeBenin: '',
  residePermanentlyBenin: '',
  otherClubMember: '',
  playSport: '',
  knownAilment: '',
  transferOutOfBenin: '',
  chargedWithCriminalOffense: '',
  marriageDuration: '',
  numberOfChildren: '',
  children: '',
  addressYears: '',
  emergencyContact: '',
  disability: '',
  sportSection: '',
  reasonToJoin: '',
  tribe: '',
  numberOfWives: '',
  educations: '',
  workExperiences: '',
  proposerPersonality: '',
  proposerKnown: '',
  // add more fields as needed
};
