import { ErrorData, FormData } from '@/types/signup';

export const steps = [
  'Email',
  'PersonalInfo',
  'Section B',
  'Section C',
  'Section D',
  'Section E',
];

export const initialFormData: FormData = {
  email: '',
  surname: '',
  firstName: '',
  dob: '',
  nationality: '',
  homeAddress: '',
  homeAddressTel: 0,
  permanentAddress: '',
  permanentAddressTel: 0,
  occupation: '',
  occupationTel: 0,
  employer: '',
  businessAddress: '',
  businessAddressTel: 0,
  nameOfBankers: '',
  employed: '',
  married: '',
  isNigeria: '',
  clubMemberRelative: '',
  dependentRelativeBenin: '',
  residePermanentlyBenin: '',
  otherClubMember: '',
  playSport: '',
  knownAilment: '',
  transferOutOfBenin: '',
  chargedWithCriminalOffense: '',
  marriageDuration: 0,
  numberOfChildren: 0,
  children: [],
  addressYears: '',
  emergencyContact: '',
  disability: '',
  sportSection: '',
  reasonToJoin: '',
  tribe: '',
  numberOfWives: '',
  // add more fields as needed
};

export const initialErrorData: ErrorData = {
  general: '',
  email: '',
  surname: '',
  firstName: '',
  dob: '',
  nationality: '',
  homeAddress: '',
  homeAddressTel: '',
  permanentAddress: '',
  permanentAddressTel: '',
  occupation: '',
  occupationTel: '',
  employer: '',
  businessAddress: '',
  businessAddressTel: '',
  nameOfBankers: '',
  employed: '',
  married: '',
  isNigeria: '',
  clubMemberRelative: '',
  dependentRelativeBenin: '',
  residePermanentlyBenin: '',
  otherClubMember: '',
  playSport: '',
  knownAilment: '',
  transferOutOfBenin: '',
  chargedWithCriminalOffense: '',
  marriageDuration: '',
  numberOfChildren: '',
  children: '',
  addressYears: '',
  emergencyContact: '',
  disability: '',
  sportSection: '',
  reasonToJoin: '',
  tribe: '',
  numberOfWives: '',
  // add more fields as needed
};
